name: christian
favicon: null
layout_spectrum: 0.48056
typography_spectrum: 0.9373869732953608
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#000000'
    - '#c0c8ef'
    - '#fe2500'
    - '#fe7d00'
    - '#52354f'
  brandStrength: 0.7937026750296354
  lightness: 0.5628689264412969
  saturation: 0.4755734133068472
  rhythmicContrast: 0.2599560609087348
purpose: []
