name: christian
favicon: null
layout_spectrum: 0.14769
typography_spectrum: 0.9373869732953608
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#000000'
    - '#68d9e7'
    - '#fdfdfe'
    - '#265a89'
    - '#e75100'
  brandStrength: 0.5625
  lightness: 0.5628689264412969
  saturation: 0.4755734133068472
  rhythmicContrast: 0.5
purpose: []
